export const tracks = [
  "/home/cdxker/Music/Ricky/DeeBaby - Never Gon End ( Official Video ) [0Gv0avlPA4E].mp3",
  "/home/cdxker/Music/Ricky/Kevin Gates - Stop Lyin [Official Audio] [Z6BHYQ10a8Y].mp3",
  "/home/cdxker/Music/Ricky/Z-RO - Lonely [H5srCqjVnw0].mp3",
  "/home/cdxker/Music/Ricky/UGK (Underground Kingz) - Da Game Been Good To Me (Official Video) [6DivB-ih4Rw].mp3",
  "/home/cdxker/Music/Drake/DRAKE  - JANICE STFU (LYRICS⧸LETRA) english-spanish [NlfyxSKrjA0].mp3",
  "/home/cdxker/Music/Ricky/$UICIDEBOY$ - I NO LONGER FEAR THE RAZOR GUARDING MY HEEL [pb0fGJXS2Qg].mp3",
  "/home/cdxker/Music/Ricky/XXXTENTACION - WingRiddenAngel (Official Audio) [I_vByxlriqA].mp3",
  "/home/cdxker/Music/Ricky/rain [osxJ5-_Ccp0].mp3",
  "/home/cdxker/Music/Ricky/XXXTENTACION - I spoke to the devil in miami, he said everything would be fine (Official Audio) [JTbMeUmQuWY].mp3",
  "/home/cdxker/Music/Ricky/XXXTENTACION - vice city (Official Audio) [h3r9myZYADc].mp3",
  "/home/cdxker/Music/Ricky/2 Chainz - I'm Different (Explicit) [e2QKlmMT8II].mp3",
  "/home/cdxker/Music/Ricky/2 Chainz - No Lie ft. Drake (Official Music Video) (Explicit Version) [uQZMaG1eO74].mp3",
  "/home/cdxker/Music/Ricky/Riley Green - Worst Way (Official Music Video) [OkktfeAR-Rk].mp3",
  "/home/cdxker/Music/Ricky/DestroyLonely- too many [zyELJlR2ucc].mp3",
  "/home/cdxker/Music/Ricky/6LACK - PRBLMS [Official Music Video] [fS9m0Ac8PCU].mp3",
  "/home/cdxker/Music/Ricky/LUCKI - Super Urus (Official Video) [fIrSkilUvHw].mp3",
  "/home/cdxker/Music/Ricky/Lucki Eck$ — Syrup Talk [HvhfEpJt6ow].mp3",
  "/home/cdxker/Music/Ricky/YoungBoy Never Broke Again - Seeming Like It [Official Audio] [Ol6x1bbVn9g].mp3",
  "/home/cdxker/Music/Ricky/2MYGRAVE & LUCKI - Lost Time (prod. Plu2o Nash) [NGgtGPwo38A].mp3",
  "/home/cdxker/Music/Ricky/LUCKI - Str8 Syrup (Official Visualizer) [_xC2eRwfg6E].mp3",
  "/home/cdxker/Music/Ricky/MurdaGang PB - 5k 6k (Official Video) [sy0-yjWyOqg].mp3",
  "/home/cdxker/Music/Ricky/Lil Yachty - Child Boy (FREESTYLE) [lCco3xoy8cY].mp3",
  "/home/cdxker/Music/Ricky/Drake - What Did I Miss？ (Official Music Video) with Lyrics [77P9wJGmAIE].mp3",
  "/home/cdxker/Music/Ricky/Kodak Black - Super Gremlin [Official Music Video] [kiB9qk4gnt4].mp3",
  "/home/cdxker/Music/Ricky/Kodak Black - Cyber Truck [Official Video] [O9x1QBbB7QM].mp3",
  "/home/cdxker/Music/Ricky/Pooh Shiesty - FDO [Official Music Video] [MPuK06zUIhc].mp3",
  "/home/cdxker/Music/Ricky/A.P.E [m0VUP8h5Dw0].mp3",
  "/home/cdxker/Music/Ricky/Im Free (feat. PoohShiesty) [QtWPSXHd4ZQ].mp3",
  "/home/cdxker/Music/Ricky/Kendrick Lamar - Bitch, Don't Kill My Vibe (Explicit) [GF8aaTu2kg0].mp3",
  "/home/cdxker/Music/Ricky/Think Its Over [-hOx0ct9Lkk].mp3",
  "/home/cdxker/Music/Ricky/Jean Grey (produced by kyslingo & lammbeats) [l05j3Mz5wqQ].mp3",
  "/home/cdxker/Music/Ricky/Dey Lying [7CePUgAQzPw].mp3",
  "/home/cdxker/Music/Ricky/Fyri/imstilldead_.mp3",
  "/home/cdxker/Music/Ricky/Fyri/_nightofthedead.mp3",
  "/home/cdxker/Music/Ricky/Fyri/Backfromthe_dead.mp3",
  "/home/cdxker/Music/Ricky/Pmg God - Hotbox (ft. Murdagang pb) [mBXfOaf9Vm8].mp3",
  "/home/cdxker/Music/Ricky/21 Savage - 3AM on Glenwood (Audio) [emmE8yDllOw].mp3",
  "/home/cdxker/Music/Ricky/Ken Car$on - Yale [kpuy4BEU644].mp3",
  "/home/cdxker/Music/Ricky/Destroy Lonely - sipped too much (Official Audio) [ht3f_qERFaA].mp3",
  "/home/cdxker/Music/Ricky/Playboi Carti -  Broke Boi (Official Music Video) [3XOETXVL424].mp3",
  "/home/cdxker/Music/Ricky/Drake - Search & Rescue (Official Visualizer) [ntp9_iznQ-0].mp3",
  "/home/cdxker/Music/Ricky/Legend [nSf3pBIX2RU].mp3",
  "/home/cdxker/Music/Ricky/Drake - Girls Love Beyonce ft. James Fauntleroy (Official Audio) [N4fExd4bTN4].mp3",
  "/home/cdxker/Music/Ricky/The Resistance [ahTCY6593HM].mp3",
  "/home/cdxker/Music/Ricky/Lil Uzi Vert - Villain (prod. SRSLy) [Ls8itPVtz5M].mp3",
  "/home/cdxker/Music/Ricky/Dover street market ~ Destroy lonely (Extended intro) [0miuLxc10-k].mp3",
  "/home/cdxker/Music/Ricky/Loe Shimmy - You Decide (Official Music Video) [dSIGRRS8Zwk].mp3",
  "/home/cdxker/Music/Ricky/Loe Shimmy - No Mileage (Official Music Video) [I98mWBXu5j0].mp3",
  "/home/cdxker/Music/Ricky/Loe Shimmy - Murda Dance (Official Video) [ZRPRAcLZj54].mp3",
  "/home/cdxker/Music/Ricky/Loe Shimmy - Where U Wanna Go (Official Music Video) [9XsmcGdwa88].mp3",
  "/home/cdxker/Music/Ricky/Hurricane Wisdom ft. Loe Shimmy - Salute (Official Music Video) [Nr1n_Q0zJug].mp3",
  "/home/cdxker/Music/Ricky/Bones - heldaghost (extended) [ClFf33jRBGM].mp3",
  "/home/cdxker/Music/Ricky/Xavier Wulf & Bones - Did You Hear？  The Roads Are Closed [LxX0DnFQwlw].mp3",
  "/home/cdxker/Music/Ricky/$UICIDEBOY$ - GREY+GREY+GREY (Lyric Video) [XQWy5B1k3L0].mp3",
];

  // "/home/cdxker/Music/Ricky/Michael Earl Craig reads ＂Bluebirds＂ [JumOzP02wrQ].mp3",
  // "/home/cdxker/Music/Ricky/Working it out [02NYWy8yNAM].mp3",
  // "/home/cdxker/Music/Ricky/lucki - super urus [slowed + reverb] [yiiw3BbXxfA].mp3",
  // "/home/cdxker/Music/Ricky/Make Them Know [GmoK54ygg_I].mp3", // Drake
  // "/home/cdxker/Music/Ricky/kendrick lamar - bitch don't kill my vibe (slowed + reverb) [jmV0TOAtaHU].mp3",
