export const defaultTracks = [
  "/home/cdxker/Music/Ricky/DeeBaby - Marz (Exclusive By： @HalfpintFilmz) [Bmy2CPU4j0Y].mp3",
  "/home/cdxker/Music/Ricky/U.O.E.N.O. (Feat. Future, Rick Ross, A$AP Rocky & Wiz Khalifa) [6I6eGVyBhGU].mp3",
  "/home/cdxker/Music/Ricky/Finesse2Tymes - Overdose [Official Music Video] [xbGprczzCFw].mp3",
  "/home/cdxker/Music/Ricky/Last nigga left.mp3",
  "/home/cdxker/Music/Ricky/Money Trees [HJNa9Ih3haA].mp3",
  "/home/cdxker/Music/Ricky/Julieta Venegas - Eres para Mí (Video) ft. Anita Tijoux [pj2ntDiXJCk].mp3",
  "/home/cdxker/Music/Ricky/Los Tigres Del Norte - Jefe De Jefes [tKQwOuTiY-A].mp3",
  "/home/cdxker/Music/Ricky/J. Cole - MIDDLE CHILD [WILNIXZr2oc].mp3",
  "/home/cdxker/Music/Ricky/Guns N' Roses - You Could Be Mine (Visualizer) [6Sp1bLrBAuQ].mp3",
  "/home/cdxker/Music/Ricky/UGK - Murder [wVjk9firE9s].mp3",
  "/home/cdxker/Music/Ricky/Rae Sremmurd, Swae Lee, Slim Jxmmi - Powerglide ft. Juicy J [95Rzsn-zjr0].mp3",
  "/home/cdxker/Music/Ricky/The Weeknd - Often (NSFW) (Official Video) [JPIhUaONiLU].mp3",
  "/home/cdxker/Music/Ricky/Lil Kee - Automatic (Official Music Video) [n6iyTwGMjME].mp3",
  "/home/cdxker/Music/Ricky/Powetemup [zDmeEe5EU3E].mp3",
  "/home/cdxker/Music/Ricky/Lil Kee - Letter 2 My Brother (Official Music Video) [ZQuWSyeFvzQ].mp3",
  "/home/cdxker/Music/Ricky/GOOSEBUMPS BY PO WET [94Vh7mm7vKM].mp3",
  "/home/cdxker/Music/Ricky/Do What Playas Do [BYYWcxqy2Ng].mp3",
  "/home/cdxker/Music/Ricky/Paul Wall & Chamillionaire - N Luv Wit My Money [xiuwfhHf1DI].mp3",
  "/home/cdxker/Music/Ricky/Chamillionaire - True (Feat. Lil' Flip & Paul Wall) [MsqFKTV9wSo].mp3",
  "/home/cdxker/Music/Ricky/My Money Gets Jealous [JyAGP5wG-B4].mp3",
  "/home/cdxker/Music/Ricky/Fredo Bang - Trust Issues (Official Music Video) [CYpvDrQvtI8].mp3",
  "/home/cdxker/Music/Ricky/Bun B - That's Gangsta [OFFICIAL VIDEO] [4h0bJZtUwEI].mp3",
  "/home/cdxker/Music/Ricky/Future - Low Life (Official Music Video) ft. The Weeknd [K_9tX4eHztY].mp3",
  "/home/cdxker/Music/Ricky/Future - Fuck Up Some Commas (Official Music Video) [wKl6umkwKfU].mp3",
  "/home/cdxker/Music/Ricky/Future - Where Ya At (Official Music Video) ft. Drake [lw3Or6eqIpI].mp3",
  "/home/cdxker/Music/Ricky/The Weeknd - Acquainted (Official Audio) [-OMptcPcw0Y].mp3",
  "/home/cdxker/Music/Ricky/Geto Boys - Mind Playing Tricks On Me (Official Video) [Explicit] [IJtHdkyo0hc].mp3",
  "/home/cdxker/Music/Ricky/Lil Wayne - John ft. Rick Ross (Explicit) (Official Music Video) ft. Rick Ross [3fumBcKC6RE].mp3",
  "/home/cdxker/Music/Ricky/Lil Wayne - Mona Lisa ft. Kendrick Lamar [ybfgomoY8Xs].mp3",
  "/home/cdxker/Music/Ricky/Future - Honest (Official Music Video) [FAeAp9MzPtk].mp3",
  "/home/cdxker/Music/Ricky/UGK - One Day [rCWH2MmlHQE].mp3",
  "/home/cdxker/Music/Ricky/Gunna - Three Headed Snake ft. Young Thug [Official Video] [0kbOaQOxiQU].mp3",
  "/home/cdxker/Music/Ricky/Three Days Grace - Burn (Audio) [_x-C7wvD0M4].mp3",
  "/home/cdxker/Music/Ricky/Jackers in My Home [6G_CILt6vuc].mp3",
  "/home/cdxker/Music/Ricky/DJ Khaled - I'm On One (Explicit Version) ft. Drake, Rick Ross, Lil Wayne [Z09lYqdxqzo].mp3",
  "/home/cdxker/Music/Ricky/DeeBaby - Never Gon End ( Official Video ) [0Gv0avlPA4E].mp3",
  "/home/cdxker/Music/Ricky/Kevin Gates - Stop Lyin [Official Audio] [Z6BHYQ10a8Y].mp3",
  "/home/cdxker/Music/Ricky/Z-RO - Lonely [H5srCqjVnw0].mp3",
  "/home/cdxker/Music/Ricky/UGK (Underground Kingz) - Da Game Been Good To Me (Official Video) [6DivB-ih4Rw].mp3",
  "/home/cdxker/Music/Ricky/$UICIDEBOY$ - I NO LONGER FEAR THE RAZOR GUARDING MY HEEL [pb0fGJXS2Qg].mp3",
  "/home/cdxker/Music/Ricky/rain [osxJ5-_Ccp0].mp3",
  "/home/cdxker/Music/Ricky/2 Chainz - I'm Different (Explicit) [e2QKlmMT8II].mp3",
  "/home/cdxker/Music/Ricky/2 Chainz - No Lie ft. Drake (Official Music Video) (Explicit Version) [uQZMaG1eO74].mp3",
  "/home/cdxker/Music/Ricky/Riley Green - Worst Way (Official Music Video) [OkktfeAR-Rk].mp3",
  "/home/cdxker/Music/Ricky/DestroyLonely- too many [zyELJlR2ucc].mp3",
  "/home/cdxker/Music/Ricky/6LACK - PRBLMS [Official Music Video] [fS9m0Ac8PCU].mp3",
  "/home/cdxker/Music/Ricky/LUCKI - Super Urus (Official Video) [fIrSkilUvHw].mp3",
  "/home/cdxker/Music/Ricky/Lucki Eck$ — Syrup Talk [HvhfEpJt6ow].mp3",
  "/home/cdxker/Music/Ricky/YoungBoy Never Broke Again - Seeming Like It [Official Audio] [Ol6x1bbVn9g].mp3",
  "/home/cdxker/Music/Ricky/2MYGRAVE & LUCKI - Lost Time (prod. Plu2o Nash) [NGgtGPwo38A].mp3",
  "/home/cdxker/Music/Ricky/LUCKI - Str8 Syrup (Official Visualizer) [_xC2eRwfg6E].mp3",
  "/home/cdxker/Music/Ricky/MurdaGang PB - 5k 6k (Official Video) [sy0-yjWyOqg].mp3",
  "/home/cdxker/Music/Ricky/Lil Yachty - Child Boy (FREESTYLE) [lCco3xoy8cY].mp3",
  "/home/cdxker/Music/Ricky/Drake - What Did I Miss？ (Official Music Video) with Lyrics [77P9wJGmAIE].mp3",
  "/home/cdxker/Music/Ricky/Kodak Black - Super Gremlin [Official Music Video] [kiB9qk4gnt4].mp3",
  "/home/cdxker/Music/Ricky/Kodak Black - Cyber Truck [Official Video] [O9x1QBbB7QM].mp3",
  "/home/cdxker/Music/Ricky/Pooh Shiesty - FDO [Official Music Video] [MPuK06zUIhc].mp3",
  "/home/cdxker/Music/Ricky/A.P.E [m0VUP8h5Dw0].mp3",
  "/home/cdxker/Music/Ricky/Im Free (feat. PoohShiesty) [QtWPSXHd4ZQ].mp3",
  "/home/cdxker/Music/Ricky/Kendrick Lamar - Bitch, Don't Kill My Vibe (Explicit) [GF8aaTu2kg0].mp3",
  "/home/cdxker/Music/Ricky/Think Its Over [-hOx0ct9Lkk].mp3",
  "/home/cdxker/Music/Ricky/Jean Grey (produced by kyslingo & lammbeats) [l05j3Mz5wqQ].mp3",
  "/home/cdxker/Music/Ricky/Dey Lying [7CePUgAQzPw].mp3",
  "/home/cdxker/Music/Ricky/Fyri/imstilldead_.mp3",
  "/home/cdxker/Music/Ricky/Fyri/_nightofthedead.mp3",
  "/home/cdxker/Music/Ricky/Fyri/Backfromthe_dead.mp3",
  "/home/cdxker/Music/Ricky/Pmg God - Hotbox (ft. Murdagang pb) [mBXfOaf9Vm8].mp3",
  "/home/cdxker/Music/Ricky/Ken Car$on - Yale [kpuy4BEU644].mp3",
  "/home/cdxker/Music/Ricky/Destroy Lonely - sipped too much (Official Audio) [ht3f_qERFaA].mp3",
  "/home/cdxker/Music/Ricky/Playboi Carti -  Broke Boi (Official Music Video) [3XOETXVL424].mp3",
  "/home/cdxker/Music/Ricky/Drake - Search & Rescue (Official Visualizer) [ntp9_iznQ-0].mp3",
  "/home/cdxker/Music/Ricky/Legend [nSf3pBIX2RU].mp3",
  "/home/cdxker/Music/Ricky/Drake - Girls Love Beyonce ft. James Fauntleroy (Official Audio) [N4fExd4bTN4].mp3",
  "/home/cdxker/Music/Ricky/21 Savage - 3AM on Glenwood (Audio) [emmE8yDllOw].mp3",
  "/home/cdxker/Music/Ricky/The Resistance [ahTCY6593HM].mp3",
  "/home/cdxker/Music/Ricky/Lil Uzi Vert - Villain (prod. SRSLy) [Ls8itPVtz5M].mp3",
  "/home/cdxker/Music/Ricky/Dover street market ~ Destroy lonely (Extended intro) [0miuLxc10-k].mp3",
  "/home/cdxker/Music/Ricky/Loe Shimmy - You Decide (Official Music Video) [dSIGRRS8Zwk].mp3",
  "/home/cdxker/Music/Ricky/Loe Shimmy - No Mileage (Official Music Video) [I98mWBXu5j0].mp3",
  "/home/cdxker/Music/Ricky/Loe Shimmy - Murda Dance (Official Video) [ZRPRAcLZj54].mp3",
  "/home/cdxker/Music/Ricky/Loe Shimmy - Where U Wanna Go (Official Music Video) [9XsmcGdwa88].mp3",
  "/home/cdxker/Music/Ricky/Hurricane Wisdom ft. Loe Shimmy - Salute (Official Music Video) [Nr1n_Q0zJug].mp3",
  "/home/cdxker/Music/Ricky/XXXTENTACION - WingRiddenAngel (Official Audio) [I_vByxlriqA].mp3",
  "/home/cdxker/Music/Ricky/XXXTENTACION - I spoke to the devil in miami, he said everything would be fine (Official Audio) [JTbMeUmQuWY].mp3",
  "/home/cdxker/Music/Ricky/XXXTENTACION - vice city (Official Audio) [h3r9myZYADc].mp3",
  "/home/cdxker/Music/Ricky/Memphis To LA [Dbn-nWusJf8].mp3",
  "/home/cdxker/Music/Ricky/LA To Memphis [UEdK06fGPxQ].mp3",
  "/home/cdxker/Music/Ricky/Last Weekend [45XZc91gjCI].mp3",
  "/home/cdxker/Music/Ricky/DRAKE  - JANICE STFU (LYRICS⧸LETRA) english-spanish [NlfyxSKrjA0].mp3",
  "/home/cdxker/Music/Ricky/Xavier Wulf, Bones - WeatherMan (Prod. Drew The Architect) [ZnbXb4cijQ4].mp3",
  "/home/cdxker/Music/Ricky/Bones - WhereTheTreesMeetTheFreeway [6Qp6Cf2J1nk].mp3",
  "/home/cdxker/Music/Ricky/Xavier Wulf & Bones - Did You Hear？  The Roads Are Closed [LxX0DnFQwlw].mp3",
  "/home/cdxker/Music/Ricky/Bones - heldaghost (extended) [ClFf33jRBGM].mp3",
  "/home/cdxker/Music/Ricky/Bones - TheRoadLessTraveled [-PiKruNUOTA].mp3",
  "/home/cdxker/Music/Ricky/$UICIDEBOY$ - GREY+GREY+GREY (Lyric Video) [XQWy5B1k3L0].mp3",
  "/home/cdxker/Music/Ricky/Institutionalized [7L1POXocFIQ].mp3",
  "/home/cdxker/Music/Ricky/These Walls [rgLO545kLME].mp3",
];

  // "/home/cdxker/Music/Ricky/Michael Earl Craig reads ＂Bluebirds＂ [JumOzP02wrQ].mp3",
  // "/home/cdxker/Music/Ricky/Working it out [02NYWy8yNAM].mp3",
  // "/home/cdxker/Music/Ricky/lucki - super urus [slowed + reverb] [yiiw3BbXxfA].mp3",
  // "/home/cdxker/Music/Ricky/Make Them Know [GmoK54ygg_I].mp3", // Drake
  // "/home/cdxker/Music/Ricky/kendrick lamar - bitch don't kill my vibe (slowed + reverb) [jmV0TOAtaHU].mp3",
